# Generated by Django 6.0.7 on 2026-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='message_type',
            field=models.CharField(choices=[('tool_call', 'Tool call'), ('text_message', 'Text message')], default='text_message', max_length=16),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='tool_call',
            field=models.CharField(blank=True, choices=[('read', 'Read'), ('write', 'Write'), ('edit', 'Edit'), ('bash', 'Bash')], max_length=16, null=True),
        ),
    ]
